#!/bin/busybox sh
busybox echo ---------------
busybox find / | busybox sort
busybox echo ---------------
busybox env | busybox sort
busybox echo ---------------
busybox pwd
busybox echo ---------------
busybox which busybox
busybox echo ---------------
